disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
  - comma
  - colon
  - line_length
  
opt_in_rules: # some rules are only opt-in

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
