# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CALORIE-TRACKER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CALORIE-TRACKER

pod "SwiftChart", :git => 'https://github.com/gpbl/SwiftChart', :branch => 'master'

end
