# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calorie-tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for calorie-tracker

  target 'calorie-trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod "SwiftChart"
end
