# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calorie tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for calorie tracker

use_frameworks!
pod 'SwiftCharts', '~> 0.6.5'
pod 'SwiftLint'

end
