# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Calorie Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftChart"
  # Pods for Calorie Tracker

  target 'Calorie TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Calorie TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
