# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-sprint-9-challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod "SwiftChart"

  # Pods for ios-sprint-9-challenge

end
