# Uncomment the next line to define a global platform for your project
platform :ios, '8.3'
swift_version = '4.2'

target 'CalorieTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalorieTracker
  pod "SwiftChart", :git => 'https://github.com/gpbl/SwiftChart', :branch => 'master'

end
