# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalorieTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all dependencies
  inhibit_all_warnings!

  # Pods for CalorieTracker
pod 'SwiftChart'
pod 'SwiftLint'
end
