disabled_rules:
  - type_name
  - unused_optional_binding
  - vertical_whitespace
  - trailing_whitespace
excluded:
- Pods
- Carthage
- Swift Style Guide.playground
- Source/ExcludedFolder
- Source/ExcludedFile.swift

line_length: 250
identifier_name:
  min_length:
    error: 2
  excluded: 
  - id
  - URL
  - GlobalAPIKey

